kind: pipeline
type: docker
name: real_rock_music_pipe

steps:
  - name: lint
    image: python:3.9-alpine
    commands:
      - 'pip install flake8'
      - 'flake8 . --max-line-length=120'
    when:
      branch:
        exclude:
          - master

  - name: build
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    privileged: true
    commands:
      - docker build . -t rrm_bot
    when:
      branch:
        - master
      event:
        - push


volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock